### ISSUE TITLE
Allow planet names to be configured for display

### ISSUE THREAD

**Issue by jwvanderbeck** [jwvanderbeck/TestFlight#43]

**Comment by jwvanderbeck** [comment]
I don't think this is an issue anymore now that RSS will be using Kopernicus.  I *think* the planets will now actually have the real names.  

Pinging @NathanKell 

Besides, this was mainly for displaying scope data which no longer exists.

**Comment by NathanKell** [comment]
Correct we have real names now

Sent by my thumbs, slowly.

**Comment by jwvanderbeck** [comment]
Excellent.  Closing this.
