### ISSUE TITLE
Two per-game settings requests

### ISSUE THREAD

**Issue by NathanKell** [jwvanderbeck/TestFlight#66]
1. "Default to max data" - all parts default to their max possible data in the save. This would be useful for sandbox-but-still-want-TestFlight.
2. "Disabled for this save" - harder, of course, but it'd be nice to have TF on for career and off for sandbox.

**Comment by jwvanderbeck** [comment]
These shouldn't be too hard to do, but I first need to implement the ability to have per game settings, which I don't currently.

**Comment by jwvanderbeck** [comment]
Features added in 1.3.0.9
https://github.com/jwvanderbeck/TestFlight/releases/tag/1.3.0.9
