### ISSUE TITLE
Migration to KSP 1.0

### ISSUE THREAD

**Issue by jwvanderbeck** [jwvanderbeck/TestFlight#67]
Need to recompile TestFlight for 1.0, but at first glance some changes will be required.
I will use this to keep track of what needs to be done, and give a friendly poke to @NathanKell in case he has any insight into changes.

* EngineModule(FX) doesn't have a requestedThrust property anymore

* [x] Engines continue to gather data even when shut down

**Comment by NathanKell** [comment]
What was requestedThrust for, anyway?
Note that ModuleEnginesFX derives from ModuleEngines, and all the changed methods are virtual, so...just use ModuleEngines.

**Comment by NathanKell** [comment]
I think you want finalThrust though?

**Comment by jwvanderbeck** [comment]
Its properly derived now instead of just a copy?  As for use, besides just being exposed from my engine wrapper, I was using it as one criteria in determining engine state, IE Ignited or not.  I may have been using it wrong but I thought requestedThrust was basically how much thrust was the player asking for by adjusting the throttle.

finalThrust sounds more like what is actually being delivered, and I was presently already using that as an additional criteria.

Do you know if requestedThrust was replaced by anything or just flat out removed?

**Comment by NathanKell** [comment]
Correct! Properly derived.
If you want isignited, just use that property.

**Comment by jwvanderbeck** [comment]
Is .isIgnited new?  I based my ignition state code on HoneyFox's original EI code, which basically uses a lot of disparate criteria to determine if an engine is ignited or not.

**Comment by NathanKell** [comment]
it's not new. Dunno why HoneyFox didn't use it.

**Comment by jwvanderbeck** [comment]
Under 1.0, engines are continuing to generate flight data even when shutdown.
