### ISSUE TITLE
Failure_ResourceLeak - Provide flexible methods to specify amount of resources to be leaked

### ISSUE THREAD

**Issue by diomedea** [jwvanderbeck/TestFlight#71]
The current structure with the definition of TestFlightFailure_ResourceLeak has the values (initialAmount, perSecondAmount) as fixed constants in the relevant config files.
IMHO, config files are best if defining behaviour for whole class of parts (e.g., all LF tanks) instead of going specifically with each single part separately. And indeed, the Squad_Tanks.cfg with TestFlightConfigStock-1-3-0-12.zip is doing with the whole class.
However, each single part has different capacity, so a fixed value can be appropriate with some, but not with all parts in a class.
The solution would be to handle percentages of the maximum capacity instead of fixed values. An initialAmount = 5% of a tank capacity, and a perSecondAmount = 1% of that tank capacity, would work better.
Moreover, there are conditions when the loss should be based on the current amount of a stored resource, rather than the maximum amount. A loss based on the amount currently stored is generally more appropriate than a loss based on what could be stored.

**Comment by jwvanderbeck** [comment]
Problem with a loss based on *current* amount is that you would then never be able to run out.

**Comment by diomedea** [comment]
Please note I didn't pretend the loss based on current amount to always be correct (it is conditional, based on what we should simulate). But, even if a resource never got to zero because of a % loss of the current amount, that would still be more accurate then always using fixed amounts. All the while, setting a failure event to deplete 100% of the current amount, would always bring to a complete loss.

I know this is calling for more complexity (something better avoided), but a way to instruct the TestFlightFailure modules to use either fixed amounts, % of maximum amounts, % of current amounts, and even to not update the amount lost every second while the current amount changes (= the perSecondAmount used could be determined from the %CurrentAmount at the time the failure occurs, not the % of a depleting CurrentAmount), would give better flexibility.

**Comment by jwvanderbeck** [comment]
Well it is easy enough to do in code, the complexity will just be in the config format where I will have to present lots of options, but I don't see anyway around that.

Should be able to get this done in my next sprint.

**Comment by jwvanderbeck** [comment]
After giving this some thought I am thinking of the following:

1) Make the `initialAmount` and `perSecondAmount

**Comment by jwvanderbeck** [comment]
https://github.com/jwvanderbeck/TestFlight/tree/Feature_71

**Comment by jwvanderbeck** [comment]
Implemented in: 
https://github.com/jwvanderbeck/TestFlight/releases/tag/1.3.0.13

If you can get a chance to test it out that would be great :)  Thanks!

**Comment by jwvanderbeck** [comment]
Build for testing: https://github.com/jwvanderbeck/TestFlight/releases/tag/1.3.0.18

**Comment by jwvanderbeck** [comment]
New build for testing:
https://github.com/jwvanderbeck/TestFlight/releases/tag/1.3.0.19
