### ISSUE TITLE
Disabled Failures still get triggered by TriggerFailure()

### ISSUE THREAD

**Issue by magico13** [jwvanderbeck/TestFlight#73]
I posted this on the forum, but figured you might not see it for a bit. I think this is the reason my code isn't stopping the failures from happening.

In short, you lower and trim the module name when you put it in the disabled list, but you don't when you check against the list.

Specifically [here](https://github.com/jwvanderbeck/TestFlight/blob/dev/TestFlightCore/TestFlightCore/TestFlightCore.cs#L680) when adding to the list, and [here](https://github.com/jwvanderbeck/TestFlight/blob/dev/TestFlightCore/TestFlightCore/TestFlightCore.cs#L584) when checking the list.

If I'm wrong and it's just that my code is wrong, then sorry for the trouble!

**Comment by magico13** [comment]
So I'm attempting to fix this on a local copy, just to make sure it's the cause. So far the system is not a big fan of not having any available failures.

First issue: an NRE because List<ITestFlightFailure> failureModules is always null if there are no failure modes.
Second issue: If you initialize that with an empty list, then the random number generator gets mad because 0 is less than 1.
````
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: Min value is greater than max value.
````

I am currently just adding a check to see if the list is still null, and if so then return null. We'll see how that goes.

**Comment by jwvanderbeck** [comment]
I saw this on the forums, but thanks for opening an issue so I didn't have to :)

Both issues make sense.  Will get them fixed ASAP.  I'm also going to followup in the forum post.

**Comment by magico13** [comment]
Ok, looks like that did it. I disabled failures, then warped about 72 Kerbin days without issue. Doing the same thing with them enabled resulted in a tank leaking after a fairly short amount of time.

Warping after re-enabling failures did not cause any failures to occur. Not sure if that's intended or not. Data, for the tank at least, appeared to be maxed out.

Here's the new code (two changes: lower and trim the module name, and return if the list is null)
````
List<ITestFlightFailure> failureModules = null;

            // Get all failure modules on the part
            // Then filter only the ones that are not disabled
            List<ITestFlightFailure> allFailureModules = TestFlightUtil.GetFailureModules(this.part);
            foreach (ITestFlightFailure fm in allFailureModules)
            {
                PartModule pm = fm as PartModule;
                if (!disabledFailures.Contains(pm.moduleName.ToLower().Trim()))
                {
                    if (failureModules == null)
                        failureModules = new List<ITestFlightFailure>();
                    failureModules.Add(fm);
                }
            }

            if (failureModules == null)
                return null;

            foreach(ITestFlightFailure fm in failureModules)
            {
                totalWeight += fm.GetFailureDetails().weight;
            }
````

**Comment by jwvanderbeck** [comment]
> Warping after re-enabling failures did not cause any failures to occur. Not sure if that's intended or not. Data, for the tank at least, appeared to be maxed out

Well disabling a failure doesn't stop the part from gaining data, so after warping for 72 days it was probably pretty reliable :)

**Comment by magico13** [comment]
> Well disabling a failure doesn't stop the part from gaining data, so after warping for 72 days it was probably pretty reliable :)

I figured that was probably the case, but I haven't actually played with the mod normally so I don't know what is expected behavior :P

**Comment by jwvanderbeck** [comment]
Both issues fixed in https://github.com/jwvanderbeck/TestFlight/tree/Hotfix_73

**Comment by jwvanderbeck** [comment]
Build for testing:
https://github.com/jwvanderbeck/TestFlight/releases/tag/1.3.0.15
